[package]
name = "TwitchBot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
websocket = "*"
json = "*"
reqwest = { version = "0.12", features = ["json"] }
serde_json = { version = "1.0" }
