name: Windows Self-hosted CI

# Trigger the workflow on push or pull request
on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# Define the job
jobs:
  build:

    # Specify the OS and the type of runner (self-hosted, windows)
    runs-on: self-hosted
    # Alternatively, if you have labeled your runner, you can use:
    # runs-on: [self-hosted, windows]

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set the PowerShell execution policy to allow scripts to run
    # - name: Set PowerShell execution policy
    #   run: |
    #     Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    #   shell: powershell
    #
    # # Install dependencies (if any, using Chocolatey for example)
    # - name: Install dependencies
    #   run: |
    #     scoop bucket add main
    #     scoop install main/git
    #     scoop install main/cmake
    #     scoop bucket add extras
    #     scoop install extras/qt-creator
    #     scoop install main/rust
    #     scoop install main/rustup
    #   shell: powershell

    # Run package
    - name: Build package
      run: |
        ./Package.bat
      shell: powershell
